---
branches:
  - main

plugins:
  - - "@semantic-release/commit-analyzer"
    - preset: conventionalcommits
      releaseRules:
      - type: docs
        release: patch
      - type: refactor
        release: patch
      - type: style
        release: patch
      - type: bug
        release: patch
      parserOpts:
        noteKeywords:
        - BREAKING CHANGE
        - BREAKING CHANGES

  - - "@semantic-release/release-notes-generator"
    - preset: conventionalcommits
    
  - - "@semantic-release/exec"
    - "generateNotesCmd": "echo RELEASE_VERSION=v${nextRelease.version} > release.env"
    
  - - "@semantic-release/changelog"
    - changelogFile: docs/CHANGELOG.md

  - - "@semantic-release/exec"
    - prepareCmd: |
        sed --in-place 's/__version__ = ".*"/__version__ = "${nextRelease.version}"/' hopprcop/__init__.py
        poetry lock --no-update
        poetry version ${nextRelease.version}

  - - semantic-release-python
    - setupPy: pyproject.toml
      repoUrl: https://gitlab.com/api/v4/projects/38643089/packages/pypi
      distDir: dist

  - - "@semantic-release/git"
    - message: |-
        chore(release): ${nextRelease.version}

        ${nextRelease.notes}
      assets:
        - docs/CHANGELOG.md
        - hopprcop/__init__.py
        - pyproject.toml
        - yarn.lock
        - sbom.json
        - LICENSE.md

  - - "@semantic-release/gitlab"
    - gitlabUrl: https://gitlab.com
      gitlabApiPathPrefix: "/api/v4"
      assets:
      - sbom.json
      - LICENSE.md

