schemaVersion: v1
kind: Transfer

stages:
  Vulnerability Check:
    plugins:
    - name: "hopprcop.hoppr_plugin.hopprcop_plugin"
      config:
        scanners: 
          - hopprcop.gemnasium.gemnasium_scanner.GemnasiumScanner
          - hopprcop.grype.grype_scanner.GrypeScanner
  Bundle:
    plugins:
    - name: hoppr.core_plugins.bundle_tar
      config:
        tarfile_name: hoppr-integration-test.tar.gz


max_processes: 3
